site_name: "oxalors home base"
site_desc: "" 
site_baseurl: ""

author: oxalorg
author_link: /about
incremental:
    - recipe

allowed:
    - .md
    - .mkd
    - .markdown
ignored:
    - README.md

# Default values
defaults:
    layout: post
    draft: False


