input_dir: 'src'
output_dir: 'public'
layout_dir: 'layouts'

md_ext:
  - '.md'
  - '.mkd'
  - '.markdown'

defaults:
  layout: 'page'
  title: 'oxalorg'
  draft: False
  author: 'ox'
  author_link: '/'

site:
  title: 'oxalorg'
  ga_id: 'UA-63732371-1'
